<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MAVPUN1121205" failures="2" tests="6" name="Surefire test" time="7.732" errors="0" timestamp="2024-04-18T17:23:49 IST">
  <testcase classname="api.test.DataDrivenTests" name="testPostuser" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at api.utilities.DataProviders.getAllData(DataProviders.java:25)
... 30 more
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testPostuser -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUserByName" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
at api.utilities.DataProviders.getUserNames(DataProviders.java:44)
... 30 more
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.UserTest" name="testPostUser" time="2.333"/>
  <testcase classname="api.test.UserTest" name="testGetUser" time="1.104"/>
  <testcase classname="api.test.UserTest" name="testUpdateUser" time="2.122"/>
  <testcase classname="api.test.UserTest" name="testDeleteUser" time="1.02"/>
</testsuite> <!-- Surefire test -->
